'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { nav } from '../data/translations/nav';
import { hero } from '../data/translations/hero';
import { stats } from '../data/translations/stats';
import { leadership } from '../data/translations/leadership';
import { services } from '../data/translations/services';
import { productsHome } from '../data/translations/productsHome';
import { projects } from '../data/translations/projects';
import { contactSection } from '../data/translations/contactSection';
import { footer } from '../data/translations/footer';
import { contactForm } from '../data/translations/contactForm';
import { productsPage } from '../data/translations/productsPage';
import { alphaNProductPage } from '../data/translations/alphaNProductPage';
import { aluBProductPage } from '../data/translations/aluBProductPage';
import { aluBMaxProductPage } from '../data/translations/aluBMaxProductPage';
import { accessories } from '../data/translations/accessories';
import { contactPage } from '../data/translations/contactPage';

export type Language = 'en' | 'fr' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
/* BEGIN removed legacy translations (will be deleted after audit)
const legacyTranslations = {
  en: {
    // Navigation
    home: 'Home',
    products: 'Products',
    services: 'Services',
    contact: 'Contact',
    phone: '+41 79 775 77 81 | +41 21 991 33 33',
    language: 'Language',
    english: 'English',
    french: 'Français',
    german: 'Deutsch',
    
    // Hero Section
    heroTitle: 'Premium Metal Building ',
    heroTitleSpan: 'Solutions',
    heroDescription: 'Engineering excellence in steel construction. From industrial warehouses to commercial complexes, we deliver durable, cost-effective metal building solutions that stand the test of time.',
    getQuote: 'Get Quote',
    
    // Stats Section
    projects: 'Projects',
    locations: 'Locations',
    experience: 'Experience',
    squareMeters: 'm² Sold',
    projectsDesc: 'Successfully completed projects across various sectors including commercial, residential, and industrial construction.',
    locationsDesc: 'With a growing presence in multiple locations, we bring our expertise to construction sites around the region.',
    experienceDesc: 'Years of combined experience in delivering high-quality construction solutions with a proven track record.',
    squareMetersDesc: 'Total area of construction we have completed, showcasing our capacity for large-scale projects.',
    
    // Leadership Message
    leadershipQuote: 'Whatever challenges you face, our extensive technical expertise in formwork allows us to find the best solutions for your needs to ensure smooth progress and deadlines are met. With us, your project is in good hands.',
    ceoName: 'Norgon Berisha',
    ceoTitle: 'CEO & Founder',
    
    // Services Section
    rental: 'Rental',
    rentalDesc: 'Our products are available for purchase directly or for rental through our partners. We also stock all the spare parts and accessories you may need.',
    technicalKnowHow: 'Technical know-how',
    technicalDesc: 'Do you have technical questions? Do you need help optimizing formwork, material rotations, and formwork solutions, or creating technical drawings or BIM models?',
    repairMaintenance: 'Repair and maintenance',
    repairDesc: 'We take care of maintaining the value of your formwork. Our service includes cleaning, panel replacement, and repairs, all the way to complete regeneration.',
    onsiteAssistance: 'On-site assistance',
    onsiteDesc: 'Do you need training for formwork installation or maintenance? Do you have a project and need advice? Our team is here to support you.',
    
    // Services Page
    whatWeOffer: 'What we offer',
    
    // Products Section
    popularProducts: 'Popular Products',
    wallFormwork: 'Wall formwork',
    alphaNDesc: 'Alpha N allows a homogeneous materialization of joints and panel holes, thus meeting the aesthetic requirements of exposed concrete.',
    aluBDesc: 'The AluB system is a manuportable aluminium formwork solution designed for the production of standard height straight concrete walls. It is particularly suitable for construction sites without cranes or in hard-to-reach areas.',
    starTecDesc: 'The StarTec XT formwork combines three anchoring methods thanks to the integrated Combi rod guide.',
    
    // Projects Section
    ourProjects: 'Our Projects',
    modernOffice: 'Modern Office Building',
    commercialConstruction: 'Commercial Construction',
    highRise: 'High-Rise Development',
    residentialComplex: 'Residential Complex',
    contemporaryMuseum: 'Contemporary Museum',
    culturalArchitecture: 'Cultural Architecture',
    
    // Contact Section
    contactTitle: 'Let our team help you choose the right product and service.',
    contactDesc: 'Speak to one of our AlphaTechSystems formwork specialists; we can help you with all your formwork needs. Let us help you with your next formwork project.',
    salesDirector: 'Sales Director for French-speaking Switzerland',
    viewLinkedIn: 'View LinkedIn profile',
    sendEmail: 'Send me an email',
    
    // Footer translations
    companyDescription: 'Specialists in the manufacture and sale of formwork equipment. AlphaTech is a family-owned company with an international reach. With 40+ years worldwide, we are proud of the confidence put in more than 40 countries. The headquarters is located in Rolle, Switzerland. Be the first. Build smart.',
    footerPopularProducts: 'Popular Products',
    alphaTechServices: 'AlphaTech Services',
    footerRental: 'Rental',
    engineering: 'Engineering',
    onSiteGuidance: 'On-site guidance',
    refurbishment: 'Refurbishment',
    preAssembly: 'Pre-assembly',
    academy: 'Academy',
    tools: 'Tools',
    downloads: 'Downloads',
    bimTools: 'BIM tools',
    wallThicknessCalculator: 'Wall thickness pressure calculator',
    columnFormsCalculator: 'Calculator for supporting column forms',
    footerContact: 'Contact',
    alphaTechFormworkSystems: 'AlphaTech Formwork Systems Ltd',
    alphaTechUK: 'AlphaTech UK',
    alphaTechSpain: 'AlphaTech Spain',
    international: 'International',
    allRightsReserved: 'All rights reserved.',
    terms: 'Terms',
    legalNotice: 'Legal Notice',
    privacyPolicyFooter: 'Privacy Policy',
    visitSocialMedia: 'Visit us on social media:',
    
    // Contact Form
    firstName: 'First and last name',
    emailAddress: 'E-mail address',
    phoneNumber: 'Phone',
    yourMessage: 'Your message',
    requiredFields: '* These fields are required',
    dataProtection: 'Data protection',
    privacyPolicy: 'I have read and accept the privacy policy',
    newsletter: 'I would like to subscribe to the Newsletter.',
    sendMessage: 'Send a message',
    
    // Products Page translations
    ourFormworkProducts: 'Our Formwork Products',
    productsHeroDesc: 'Discover our premium formwork solutions designed for efficiency, durability, and versatility across all construction projects.',
    allProducts: 'All products',
    productsWallFormwork: 'Wall formwork',
    columnFormwork: 'Column formwork',
    showeringTower: 'Showering Tower',
    accessPlatforms: 'Access and security platforms',
    accessories: 'Accessories',
    availableRental: 'Available for rental',
    craneIndependent: 'Crane independent',
    heavyFormwork: 'Heavy formwork',
    singleSidedFormwork: 'Single-sided anchored formwork',
    hydraulicClimber: 'Hydraulic climber',
    productsAlphaNDesc: 'Alpha N allows a homogeneous materialization of joints and panel holes, thus meeting the aesthetic requirements of exposed concrete.',
    productsAluBDesc: 'AluB is a universal, hand-held formwork made of aluminum. Lightweight and easy to handle, it offers versatility for a wide range of construction applications.',
    starTecXTDesc: 'The StarTec XT formwork combines three anchoring methods thanks to the integrated Combi rod guide, offering exceptional versatility and efficiency.',
    aluminumConstruction: 'Aluminum Construction',
    universalApplication: 'Universal Application',
    tripleAnchoringSystem: 'Triple Anchoring System',
    viewDetails: 'View Details',
    compareProducts: 'Compare Our Products',
    compareDesc: 'Find the perfect formwork solution for your specific construction needs.',
    features: 'Features',
    material: 'Material',
    aluminum: 'Aluminum',
    aluminumSteel: 'Aluminum with steel reinforcement',
    steel: 'Steel',
    weight: 'Weight',
    lightweight: 'Lightweight (20 kg/m²)',
    medium: 'Medium (23 kg/m²)',
    heavyDuty: 'Heavy-duty (45 kg/m²)',
    freshConcretePressure: 'Fresh Concrete Pressure',
    bestFor: 'Best For',
    smallMediumProjects: 'Small to medium projects',
    mediumLargeProjects: 'Medium to large projects',
    largeCommercial: 'Large commercial & infrastructure',
    specialFeature: 'Special Feature',
    optimizedHeights: 'Optimized heights',
    enhancedDurability: 'Enhanced durability',
    tripleAnchoring: 'Triple anchoring system',
    needHelpChoosing: 'Need help choosing the right formwork?',
    expertConsultation: 'Our team of experts can help you determine the best formwork solution for your specific construction needs. Contact us today for a personalized consultation.',
    contactUs: 'Contact Us',
    
    // AlphaN Product Page translations
    alphaNHeroDesc: 'Lightweight. Modular. Efficient. The next generation of portable formwork.',
    alphaNProductDesc: 'Every construction site is different, with its own requirements. The Alpha N formwork system has been designed to meet these requirements with maximum flexibility. Modular, it adapts to all configurations, ensuring that you always have the right equipment, regardless of the complexity of the structure.',
    details: 'Details',
    qualityFacingConcrete: 'Quality of facing concrete assured',
    qualityFacingDesc: 'Thanks to a symmetrical layout of the rod passages and various panel sizes, Alpha N allows a homogeneous materialization of joints and panel holes, thus meeting the aesthetic requirements of exposed concrete.',
    assemblyAnchoringSystem: 'Assembly and anchoring system',
    alphaTechLock: 'AlphaTECH lock:',
    alphaTechLockDesc: 'quick fastening of panels with simple hammer blows',
    multiFunctionCrossbeam: 'Multi-function crossbeam:',
    multiFunctionDesc: 'Welded DW nuts for quick installation of accessories with one piece – the flange screw',
    anchoringSystem: 'Anchoring system:',
    anchoringSystemDesc: 'DW Ø 15 mm with 80 kN load capacity double-sided',
    easeOfUse: 'Ease of use',
    identicalFaces: 'Identical faces:',
    identicalFacesDesc: 'no mistakes, faster installation',
    layout: 'Layout:',
    layoutDesc: 'symmetrical horizontal and vertical installation',
    corners: 'Corners:',
    cornersDesc: 'corner solutions that can be implemented for all wall thicknesses, with a complete range:',
    cornerTypes: 'Inside, outside, hinged and slashing corners',
    outerCorners: 'Three outer corners (0.5 cm and 10 cm on each side)',
    insideCorner: 'Inside corner (30 cm on each side)',
    technicalSpecifications: 'Technical Specifications',
    maximumAdaptability: 'Maximum adaptability',
    panelDimensions: 'Panel dimensions:',
    heights: 'Heights:',
    heightsValues: '330 cm, 270 cm, 150 cm',
    widths: 'Widths:',
    widthsValues: 'ranging from from 270 cm to 30 cm (240 cm, 120 cm, 90 cm, 60 cm, 50 cm, 45 cm, 40 cm)',
    customSizes: 'Other custom sizes available',
    adaptabilityDesc: 'These dimensions make it possible to quickly adapt to the geometry of the building and to achieve all the usual wall thicknesses without compensation parts.',
    technicalPerformance: 'Technical performance',
    permissiblePressure: 'Permissible pressure',
    pressureValue: '80 kN/m² for a single wall',
    materialSpec: 'high-dimensional, torsion-resistant steel',
    coating: 'Coating',
    coatingValue: '220 g/m² phenolic resin on both sides',
    painting: 'Painting',
    paintingValue: 'electromatic',
    crane: 'Crane',
    craneValue: 'requires the use of a crane',
    applicationExamples: 'Application Examples',
    residentialConstruction: 'Residential Construction',
    residentialDesc: 'Perfect for foundation walls and basement construction in residential projects.',
    commercialBuildings: 'Commercial Buildings',
    commercialDesc: 'Ideal for small to medium-sized commercial construction projects.',
    infrastructureProjects: 'Infrastructure Projects',
    infrastructureDesc: 'Used in smaller infrastructure elements like retaining walls and foundations.',
    interestedInAlphaFix: 'Interested in AluFix for your project?',
    alphaFixContactDesc: 'Contact our team for a quote or to learn more about how AluFix can benefit your construction project.',
    youMightAlsoLike: 'You Might Also Like',
    aluStarDesc: 'Heavy-duty aluminum formwork system for large-scale concrete structures.',
    plyformDesc: 'Versatile plywood formwork system for walls, columns, and slabs.',
    tableFormDesc: 'Flying form system for efficient slab construction in high-rise buildings.',
    
    // AluB Product Page translations
    aluBHeroDesc: 'Universal. Durable. Versatile. The aluminum formwork system for all your construction needs.',
    aluBProductDesc: 'The AluB system is a manuportable aluminium formwork solution designed for the production of standard height straight concrete walls. It is particularly suitable for construction sites without cranes or in hard-to-reach areas.',
    keyBenefits: 'Key Benefits',
    manuportable: 'Manuportable',
    manuportableDesc: 'No need for a crane – easy handling by one person.',
    lightweightEfficient: 'Lightweight and efficient',
    lightweightEfficientDesc: 'Approx. 21.5 kg/m² for an excellent weight/strength ratio.',
    optimalModularity: 'Optimal modularity',
    optimalModularityDesc: 'Wide choice of standard panels (270 x 90, 60, 50, 30 cm) + custom-made construction.',
    qualityFinish: 'Quality finish',
    qualityFinishDesc: '15 mm all-birch plywood, 220 g film – 1.5 mm plastic film option available.',
    aluBAdaptability: 'Adaptability',
    aluBAdaptabilityPoint1: 'Possibility of adding a wooden furring (up to 10 cm) between two panels to adjust the width.',
    aluBAdaptabilityPoint2: 'Corner and stabilization accessories available for all configurations.',
    enhancedSecurity: 'Enhanced security',
    enhancedSecurityPoint1: 'Service consoles, railing posts, push-pull props included.',
    enhancedSecurityPoint2: 'Stability and access accessories painted for better visibility.',
    technicalCharacteristics: 'Technical Characteristics',
    specification: 'Specification',
    aluBDetailsHeader: 'Details',
    materialAluminum: 'Aluminum (mostly recycled)',
    panelCovering: 'Panel covering',
    panelCoveringValue: '15 mm birch plywood, 220 g film – optional 1.5 mm plastic film',
    edgeProfileThickness: 'Edge profile thickness',
    edgeProfileValue: '100 mm',
    standardDimensionsHeight: 'Standard Dimensions - Height',
    standardHeightValue: '270 cm',
    standardDimensionsWidths: 'Standard Dimensions - Widths',
    standardWidthsValue: '90, 60, 50, 30 cm + custom-made',
    aluBWeight: 'Weight',
    aluBWeightValue: '21.5 kg/m² | Panel 270 x 90 cm ≈ 65 kg',
    aluBAnchoring: 'Anchoring',
    anchoringValue: 'DW system Ø15 mm, double-sided clamping',
    numberOfRods: 'Number of rods',
    numberOfRodsValue: '3 vertical rods for H 270 cm and 300 cm panels',
    permissibleConcretePressure: 'Permissible concrete pressure',
    concretePressureValue: '30 tons/m²',
    aluBCommercialConstruction: 'Commercial Construction',
    aluBCommercialConstructionDesc: 'Ideal for medium to large commercial buildings with complex concrete requirements.',
    multiStoryBuildings: 'Multi-story Buildings',
    multiStoryBuildingsDesc: 'Perfect for constructing walls in multi-story residential and office buildings.',
    infrastructureBridges: 'Infrastructure Projects',
    infrastructureBridgesDesc: 'Used in bridges, tunnels, and other medium-sized infrastructure elements.',
    interestedInAluStar: 'Interested in AluStar for your project?',
    aluStarContactDesc: 'Contact our team for a quote or to learn more about how AluStar can benefit your construction project.',
    servicesCtaDesc: 'Contact us today to discuss how our services can help bring your construction project to life.',
    getInTouch: 'Get in Touch',
    
    // Contact Page
    contactUsTitle: 'Contact Us',
    contactFormName: 'Name',
    contactFormEmail: 'Email',
    contactFormMessage: 'Message',
    contactFormSend: 'Send Message',
    contactInformation: 'Contact Information',
    contactAddress: 'Address',
    contactAddressValue: 'Chemin des Vernes 5, 1180 Rolle, Switzerland',
    contactPhone: 'Phone',
    contactPhoneValue: '+41 79 775 77 81 | +41 21 991 33 33',
    contactEmailLabel: 'Email',
    contactEmailValue: 'info@alphatechsystemes.com',
    workingHours: 'Working Hours',
    workingHoursWeekdays: 'Monday - Friday: 8:00 AM - 18:00 PM',
    workingHoursWeekends: 'Saturday - Sunday: Closed',
    
    // Countries
    swiss: 'Swiss',
    france: 'France',
    germany: 'Germany',
    other: 'Other'
  },
  fr: {
    // Navigation
    home: 'Accueil',
    products: 'Produits',
    services: 'Services',
    contact: 'Contact',
    phone: '+41 79 775 77 81 | +41 21 991 33 33',
    language: 'Langue',
    english: 'English',
    french: 'Français',
    german: 'Deutsch',
    
    // Hero Section
    heroTitle: 'Solutions de Construction',
    heroTitleSpan: 'Métallique Premium',
    heroDescription: 'Excellence en ingénierie dans la construction en acier. Des entrepôts industriels aux complexes commerciaux, nous livrons des solutions de bâtiments métalliques durables et rentables qui résistent à l\'épreuve du temps.',
    getQuote: 'Obtenir un Devis',
    
    // Stats Section
    projects: 'Projets',
    locations: 'Emplacements',
    experience: 'Expérience',
    squareMeters: 'm² Vendu',
    projectsDesc: 'Projets menés à bien dans divers secteurs, notamment la construction commerciale, résidentielle et industrielle.',
    locationsDesc: 'Avec une présence croissante dans plusieurs endroits, nous apportons notre expertise sur les chantiers de la région.',
    experienceDesc: 'Années d\'expérience combinée dans la fourniture de solutions de construction de haute qualité avec des références éprouvées.',
    squareMetersDesc: 'Superficie totale de construction que nous avons réalisée, démontrant notre capacité à gérer des projets d\'envergure.',
    
    // Leadership Message
    leadershipQuote: 'Quels que soient les défis auxquels vous faites face, notre vaste expertise technique en coffrage nous permet de trouver les meilleures solutions pour vos besoins afin d\'assurer un progrès fluide et que les délais soient respectés. Avec nous, votre projet est entre de bonnes mains.',
    ceoName: 'Norgon Berisha',
    ceoTitle: 'PDG et Fondateur',
    
    // Services Section
    rental: 'Location',
    rentalDesc: 'Nos produits sont disponibles à l\'achat directement ou à la location par l\'intermédiaire de nos partenaires. Nous stockons également toutes les pièces de rechange et accessoires dont vous pourriez avoir besoin.',
    technicalKnowHow: 'Savoir-faire technique',
    technicalDesc: 'Avez-vous des questions techniques ? Avez-vous besoin d\'aide pour optimiser le coffrage, les rotations de matériaux et les solutions de coffrage, ou créer des dessins techniques ou des modèles BIM ?',
    repairMaintenance: 'Réparation et maintenance',
    repairDesc: 'Nous prenons soin de maintenir la valeur de votre coffrage. Notre service comprend le nettoyage, le remplacement de panneaux et les réparations, jusqu\'à la régénération complète.',
    onsiteAssistance: 'Assistance sur site',
    onsiteDesc: 'Avez-vous besoin de formation pour l\'installation ou la maintenance du coffrage ? Avez-vous un projet et besoin de conseils ? Notre équipe est là pour vous soutenir.',
    
    // Products Section
    popularProducts: 'Produits Populaires',
    wallFormwork: 'Coffrage mural',
    alphaNDesc: 'Alpha N permet une matérialisation homogène des joints et des trous de panneaux, répondant ainsi aux exigences esthétiques du béton apparent.',
    aluBDesc: 'Le système AluB est une solution de coffrage en aluminium manuportable conçue pour la production de murs en béton droits de hauteur standard. Il est particulièrement adapté aux chantiers sans grues ou dans des zones difficiles d\'accès.',
    starTecDesc: 'Le coffrage StarTec XT combine trois méthodes d\'ancrage grâce au guide de tige Combi intégré.',
    
    // Projects Section
    ourProjects: 'Nos Projets',
    modernOffice: 'Immeuble de Bureaux Moderne',
    commercialConstruction: 'Construction Commerciale',
    highRise: 'Développement de Grande Hauteur',
    residentialComplex: 'Complexe Résidentiel',
    contemporaryMuseum: 'Musée Contemporain',
    culturalArchitecture: 'Architecture Culturelle',
    
    // Contact Section
    contactTitle: 'Laissez notre équipe vous aider à choisir le bon produit et service.',
    contactDesc: 'Parlez à l\'un de nos spécialistes en coffrage AlphaTechSystems ; nous pouvons vous aider avec tous vos besoins en coffrage. Laissez-nous vous aider avec votre prochain projet de coffrage.',
    salesDirector: 'Directeur des Ventes pour la Suisse Romande',
    viewLinkedIn: 'Voir le profil LinkedIn',
    sendEmail: 'Envoyez-moi un email',
    
    // Contact Form
    firstName: 'Prénom et nom',
    emailAddress: 'Adresse e-mail',
    phoneNumber: 'Téléphone',
    yourMessage: 'Votre message',
    requiredFields: '* Ces champs sont obligatoires',
    dataProtection: 'Protection des données',
    privacyPolicy: 'J\'ai lu et j\'accepte la politique de confidentialité',
    newsletter: 'Je souhaite m\'abonner à la Newsletter.',
    sendMessage: 'Envoyer un message',
    
    // Footer translations
    companyDescription: 'Spécialistes dans la fabrication et la vente d\'équipements de coffrage. AlphaTech est une entreprise familiale avec une portée internationale. Avec plus de 40 ans dans le monde, nous sommes fiers de la confiance accordée dans plus de 40 pays. Le siège social est situé à Haiterbach, en Allemagne. Soyez les premiers. Construisez intelligemment.',
    footerPopularProducts: 'Produits Populaires',
    alphaTechServices: 'Services AlphaTech',
    footerRental: 'Location',
    engineering: 'Ingénierie',
    onSiteGuidance: 'Accompagnement sur site',
    refurbishment: 'Rénovation',
    preAssembly: 'Pré-assemblage',
    academy: 'Académie',
    tools: 'Outils',
    downloads: 'Téléchargements',
    bimTools: 'Outils BIM',
    wallThicknessCalculator: 'Calculateur de pression d\'épaisseur de mur',
    columnFormsCalculator: 'Calculateur pour formes de colonnes de support',
    footerContact: 'Contact',
    alphaTechFormworkSystems: 'AlphaTech Formwork Systems Ltd',
    alphaTechUK: 'AlphaTech UK',
    alphaTechSpain: 'AlphaTech Spain',
    international: 'International',
    allRightsReserved: 'Tous droits réservés.',
    terms: 'Conditions',
    legalNotice: 'Mentions Légales',
    privacyPolicyFooter: 'Politique de Confidentialité',
    visitSocialMedia: 'Visitez-nous sur les réseaux sociaux:',
    
    // Products Page translations
    ourFormworkProducts: 'Nos Produits de Coffrage',
    productsHeroDesc: 'Découvrez nos solutions de coffrage premium conçues pour l\'efficacité, la durabilité et la polyvalence dans tous les projets de construction.',
    allProducts: 'Tous les produits',
    productsWallFormwork: 'Coffrage de mur',
    columnFormwork: 'Coffrage de colonne',
    showeringTower: 'Tour de douche',
    accessPlatforms: 'Plateformes d\'accès et de sécurité',
    accessories: 'Accessoires',
    availableRental: 'Disponible à la location',
    craneIndependent: 'Indépendant de la grue',
    heavyFormwork: 'Coffrage lourd',
    singleSidedFormwork: 'Coffrage ancré unilatéral',
    hydraulicClimber: 'Grimpeur hydraulique',
    productsAlphaNDesc: 'Alpha N permet une matérialisation homogène des joints et des trous de panneaux, répondant ainsi aux exigences esthétiques du béton apparent.',
    productsAluBDesc: 'AluB est un coffrage universel portatif en aluminium. Léger et facile à manipuler, il offre une polyvalence pour une large gamme d\'applications de construction.',
    starTecXTDesc: 'Le coffrage StarTec XT combine trois méthodes d\'ancrage grâce au guide de tige Combi intégré, offrant une polyvalence et une efficacité exceptionnelles.',
    aluminumConstruction: 'Construction en Aluminium',
    universalApplication: 'Application Universelle',
    tripleAnchoringSystem: 'Système d\'Ancrage Triple',
    viewDetails: 'Voir les Détails',
    compareProducts: 'Comparer Nos Produits',
    compareDesc: 'Trouvez la solution de coffrage parfaite pour vos besoins de construction spécifiques.',
    features: 'Caractéristiques',
    material: 'Matériau',
    aluminum: 'Aluminium',
    aluminumSteel: 'Aluminium avec renfort en acier',
    steel: 'Acier',
    weight: 'Poids',
    lightweight: 'Léger (20 kg/m²)',
    medium: 'Moyen (23 kg/m²)',
    heavyDuty: 'Usage intensif (45 kg/m²)',
    freshConcretePressure: 'Pression du Béton Frais',
    bestFor: 'Idéal Pour',
    smallMediumProjects: 'Projets petits à moyens',
    mediumLargeProjects: 'Projets moyens à grands',
    largeCommercial: 'Grand commercial et infrastructure',
    specialFeature: 'Caractéristique Spéciale',
    optimizedHeights: 'Hauteurs optimisées',
    enhancedDurability: 'Durabilité renforcée',
    tripleAnchoring: 'Système d\'ancrage triple',
    needHelpChoosing: 'Besoin d\'aide pour choisir le bon coffrage?',
    expertConsultation: 'Notre équipe d\'experts peut vous aider à déterminer la meilleure solution de coffrage pour vos besoins de construction spécifiques. Contactez-nous aujourd\'hui pour une consultation personnalisée.',
    contactUs: 'Nous Contacter',
    
    // AlphaN Product Page translations
    alphaNHeroDesc: 'Léger. Modulaire. Efficace. La nouvelle génération de coffrage portable.',
    alphaNProductDesc: 'Chaque chantier est différent, avec ses propres exigences. Le système de coffrage Alpha N a été conçu pour répondre à ces exigences avec une flexibilité maximale. Modulaire, il s\'adapte à toutes les configurations, garantissant que vous avez toujours le bon équipement, quelle que soit la complexité de la structure.',
    details: 'Détails',
    qualityFacingConcrete: 'Qualité du béton de parement assurée',
    qualityFacingDesc: 'Grâce à une disposition symétrique des passages de tiges et à diverses tailles de panneaux, Alpha N permet une matérialisation homogène des joints et des trous de panneaux, répondant ainsi aux exigences esthétiques du béton apparent.',
    assemblyAnchoringSystem: 'Système d\'assemblage et d\'ancrage',
    alphaTechLock: 'Verrou AlphaTECH:',
    alphaTechLockDesc: 'fixation rapide des panneaux avec de simples coups de marteau',
    multiFunctionCrossbeam: 'Poutre transversale multifonction:',
    multiFunctionDesc: 'Écrous DW soudés pour une installation rapide des accessoires avec une pièce - la vis à bride',
    anchoringSystem: 'Système d\'ancrage:',
    anchoringSystemDesc: 'DW Ø 15 mm avec capacité de charge de 80 kN double face',
    easeOfUse: 'Facilité d\'utilisation',
    identicalFaces: 'Faces identiques:',
    identicalFacesDesc: 'pas d\'erreurs, installation plus rapide',
    layout: 'Disposition:',
    layoutDesc: 'installation horizontale et verticale symétrique',
    corners: 'Coins:',
    cornersDesc: 'solutions d\'angle qui peuvent être mises en œuvre pour toutes les épaisseurs de mur, avec une gamme complète:',
    cornerTypes: 'Coins intérieurs, extérieurs, articulés et tranchants',
    outerCorners: 'Trois coins extérieurs (0,5 cm et 10 cm de chaque côté)',
    insideCorner: 'Coin intérieur (30 cm de chaque côté)',
    technicalSpecifications: 'Spécifications Techniques',
    maximumAdaptability: 'Adaptabilité maximale',
    panelDimensions: 'Dimensions des panneaux:',
    heights: 'Hauteurs:',
    heightsValues: '330 cm, 270 cm, 150 cm',
    widths: 'Largeurs:',
    widthsValues: 'allant de 270 cm à 30 cm (240 cm, 120 cm, 90 cm, 60 cm, 50 cm, 45 cm, 40 cm)',
    customSizes: 'Autres tailles personnalisées disponibles',
    adaptabilityDesc: 'Ces dimensions permettent de s\'adapter rapidement à la géométrie du bâtiment et d\'atteindre toutes les épaisseurs de mur habituelles sans pièces de compensation.',
    technicalPerformance: 'Performance technique',
    permissiblePressure: 'Pression admissible',
    pressureValue: '80 kN/m² pour un mur simple',
    materialSpec: 'acier haute dimension, résistant à la torsion',
    coating: 'Revêtement',
    coatingValue: '220 g/m² résine phénolique des deux côtés',
    painting: 'Peinture',
    paintingValue: 'électromatique',
    crane: 'Grue',
    craneValue: 'nécessite l\'utilisation d\'une grue',
    applicationExamples: 'Exemples d\'Application',
    residentialConstruction: 'Construction Résidentielle',
    residentialDesc: 'Parfait pour les murs de fondation et la construction de sous-sols dans les projets résidentiels.',
    commercialBuildings: 'Bâtiments Commerciaux',
    commercialDesc: 'Idéal pour les projets de construction commerciale de petite à moyenne taille.',
    infrastructureProjects: 'Projets d\'Infrastructure',
    infrastructureDesc: 'Utilisé dans les éléments d\'infrastructure plus petits comme les murs de soutènement et les fondations.',
    interestedInAlphaFix: 'Intéressé par AluFix pour votre projet?',
    alphaFixContactDesc: 'Contactez notre équipe pour un devis ou pour en savoir plus sur la façon dont AluFix peut bénéficier à votre projet de construction.',
    youMightAlsoLike: 'Vous Pourriez Aussi Aimer',
    aluStarDesc: 'Système de coffrage en aluminium robuste pour les structures en béton à grande échelle.',
    plyformDesc: 'Système de coffrage en contreplaqué polyvalent pour murs, colonnes et dalles.',
    tableFormDesc: 'Système de forme volante pour une construction efficace de dalles dans les immeubles de grande hauteur.',
    
    // AluB Product Page translations
    aluBHeroDesc: 'Universel. Durable. Polyvalent. Le système de coffrage en aluminium pour tous vos besoins de construction.',
    aluBProductDesc: 'Le système AluB est une solution de coffrage en aluminium manuportable conçue pour la production de murs en béton droits de hauteur standard. Il est particulièrement adapté aux chantiers sans grues ou dans les zones difficiles d\'accès.',
    keyBenefits: 'Avantages Clés',
    manuportable: 'Manuportable',
    manuportableDesc: 'Pas besoin de grue – manipulation facile par une seule personne.',
    lightweightEfficient: 'Léger et efficace',
    lightweightEfficientDesc: 'Environ 21,5 kg/m² pour un excellent rapport poids/résistance.',
    optimalModularity: 'Modularité optimale',
    optimalModularityDesc: 'Large choix de panneaux standards (270 x 90, 60, 50, 30 cm) + construction sur mesure.',
    qualityFinish: 'Finition de qualité',
    qualityFinishDesc: 'Contreplaqué de bouleau de 15 mm, film 220 g – option film plastique 1,5 mm disponible.',
    aluBAdaptability: 'Adaptabilité',
    aluBAdaptabilityPoint1: 'Possibilité d\'ajouter un lattage en bois (jusqu\'à 10 cm) entre deux panneaux pour ajuster la largeur.',
    aluBAdaptabilityPoint2: 'Accessoires d\'angle et de stabilisation disponibles pour toutes les configurations.',
    enhancedSecurity: 'Sécurité renforcée',
    enhancedSecurityPoint1: 'Consoles de service, poteaux de garde-corps, étais de poussée-traction inclus.',
    enhancedSecurityPoint2: 'Accessoires de stabilité et d\'accès peints pour une meilleure visibilité.',
    technicalCharacteristics: 'Caractéristiques Techniques',
    specification: 'Spécification',
    aluBDetailsHeader: 'Détails',
    materialAluminum: 'Aluminium (principalement recyclé)',
    panelCovering: 'Revêtement des panneaux',
    panelCoveringValue: 'Contreplaqué de bouleau 15 mm, film 220 g – film plastique 1,5 mm en option',
    edgeProfileThickness: 'Épaisseur du profil de bord',
    edgeProfileValue: '100 mm',
    standardDimensionsHeight: 'Dimensions Standard - Hauteur',
    standardHeightValue: '270 cm',
    standardDimensionsWidths: 'Dimensions Standard - Largeurs',
    standardWidthsValue: '90, 60, 50, 30 cm + sur mesure',
    aluBWeight: 'Poids',
    aluBWeightValue: '21,5 kg/m² | Panneau 270 x 90 cm ≈ 65 kg',
    aluBAnchoring: 'Ancrage',
    anchoringValue: 'Système DW Ø15 mm, serrage double face',
    numberOfRods: 'Nombre de tiges',
    numberOfRodsValue: '3 tiges verticales pour panneaux H 270 cm et 300 cm',
    permissibleConcretePressure: 'Pression admissible du béton',
    concretePressureValue: '30 tonnes/m²',
    aluBCommercialConstruction: 'Construction Commerciale',
    aluBCommercialConstructionDesc: 'Idéal pour les bâtiments commerciaux moyens à grands avec des exigences complexes en béton.',
    multiStoryBuildings: 'Bâtiments à Étages Multiples',
    multiStoryBuildingsDesc: 'Parfait pour construire des murs dans des bâtiments résidentiels et de bureaux à plusieurs étages.',
    infrastructureBridges: 'Projets d\'Infrastructure',
    infrastructureBridgesDesc: 'Utilisé dans les ponts, tunnels et autres éléments d\'infrastructure de taille moyenne.',
    interestedInAluStar: 'Intéressé par AluStar pour votre projet?',
    aluStarContactDesc: 'Contactez notre équipe pour un devis ou pour en savoir plus sur la façon dont AluStar peut bénéficier à votre projet de construction.',
    aluFixDesc: 'Système de coffrage léger et portable pour une construction efficace.',
    
    // Countries
    swiss: 'Suisse',
    france: 'France',
    germany: 'Allemagne',
    other: 'Autre',
    
    // Services Page
    whatWeOffer: 'Ce que nous offrons',
    servicesDescription: 'Nous offrons des solutions de construction complètes adaptées à vos besoins spécifiques, de la planification à l\'exécution.',
    constructionPlanning: 'Planification de construction',
    constructionPlanningDesc: 'Services de planification complets qui garantissent que votre projet commence avec une base solide. Nos experts analysent les exigences, développent des calendriers et créent des plans d\'exécution détaillés.',
    projectManagement: 'Gestion de projet',
    projectManagementDesc: 'Services de gestion de projet de bout en bout qui garantissent que votre projet de construction est terminé à temps, dans le budget et selon les normes de qualité les plus élevées.',
    formworkSolutions: 'Solutions de coffrage',
    formworkSolutionsDesc: 'Solutions de coffrage spécialisées pour structures en béton de tous types. Nous fournissons des systèmes avancés qui garantissent précision, efficacité et sécurité.',
    concreteWorks: 'Travaux de béton',
    concreteWorksDesc: 'Services de béton experts incluant coulage, finition et traitements spécialisés. Nous garantissons durabilité, attrait esthétique et intégrité structurelle.',
    consultingServices: 'Services de conseil',
    consultingServicesDesc: 'Conseil professionnel sur les méthodes de construction, la sélection de matériaux et les solutions techniques pour optimiser l\'efficacité et la rentabilité de votre projet.',
    equipmentRental: 'Location d\'équipement',
    equipmentRentalDesc: 'Services complets de location d\'équipement incluant systèmes de coffrage, échafaudages et outils de construction spécialisés pour soutenir les besoins de votre projet.',
    learnMore: 'En savoir plus',
    whyChooseOurServices: 'Pourquoi choisir nos services',
    qualityAssurance: 'Assurance qualité',
    qualityAssuranceDesc: 'Nous maintenons les normes de qualité les plus élevées dans tous nos services, garantissant des résultats durables et fiables.',
    timelyDelivery: 'Livraison ponctuelle',
    timelyDeliveryDesc: 'Nous comprenons l\'importance des délais et nous nous assurons que tous les projets sont terminés dans les temps.',
    expertTeam: 'Équipe d\'experts',
    expertTeamDesc: 'Notre équipe est composée de professionnels expérimentés avec une connaissance approfondie dans diverses spécialités de construction.',
    readyToStartProject: 'Prêt à commencer votre projet ?',
    servicesCtaDesc: 'Contactez-nous aujourd\'hui pour discuter de la façon dont nos services peuvent aider à donner vie à votre projet de construction.',
    getInTouch: 'Nous contacter',
    
    // Contact Page
    contactUsTitle: 'Nous contacter',
    contactFormName: 'Nom',
    contactFormEmail: 'E-mail',
    contactFormMessage: 'Message',
    contactFormSend: 'Envoyer le message',
    contactInformation: 'Informations de contact',
    contactAddress: 'Adresse',
    contactAddressValue: 'Chemin des Vernes 5, 1180 Rolle, Switzerland',
    contactPhone: 'Téléphone',
    contactPhoneValue: '+41 79 775 77 81 | +41 21 991 33 33',
    contactEmailLabel: 'E-mail',
    contactEmailValue: 'info@alphatechsystemes.com',
    workingHours: 'Heures d\'ouverture',
    workingHoursWeekdays: 'Lundi - Vendredi : 8h00 - 17h00',
    workingHoursWeekends: 'Samedi - Dimanche : Fermé'
  },
  de: {
    // Navigation
    home: 'Startseite',
    products: 'Produkte',
    services: 'Dienstleistungen',
    contact: 'Kontakt',
    phone: '+41 79 775 77 81 | +41 21 991 33 33',
    language: 'Sprache',
    english: 'English',
    french: 'Français',
    german: 'Deutsch',
    
    // Hero Section
    heroTitle: 'Premium Metallbau',
    heroTitleSpan: 'Lösungen',
    heroDescription: 'Ingenieurexzellenz im Stahlbau. Von Industrielagern bis hin zu Gewerbeanlagen liefern wir langlebige, kosteneffektive Metallbaulösungen, die der Zeit standhalten.',
    getQuote: 'Angebot Erhalten',
    
    // Stats Section
    projects: 'Projekte',
    locations: 'Standorte',
    experience: 'Erfahrung',
    squareMeters: 'm² Verkauft',
    projectsDesc: 'Erfolgreich abgeschlossene Projekte in verschiedenen Bereichen, einschließlich gewerblicher, gewerblicher und industrieller Bauvorhaben.',
    locationsDesc: 'Mit wachsender Präsenz an mehreren Standorten bringen wir unser Know-how auf Baustellen in der Region.',
    experienceDesc: 'Jahre kombinierte Erfahrung in der Bereitstellung hochwertiger Baulösungen mit nachgewiesener Erfolgsbilanz.',
    squareMetersDesc: 'Gesamtfläche der von uns fertiggestellten Bauarbeiten, die unsere Kapazität für Großprojekte zeigt.',
    
    // Leadership Message
    leadershipQuote: 'Welchen Herausforderungen Sie auch gegenüberstehen, unsere umfassende technische Expertise in der Schalung ermöglicht es uns, die besten Lösungen für Ihre Bedürfnisse zu finden, um einen reibungslosen Fortschritt zu gewährleisten und Termine einzuhalten. Bei uns ist Ihr Projekt in guten Händen.',
    ceoName: 'Norgon Berisha',
    ceoTitle: 'CEO & Gründer',
    
    // Services Section
    rental: 'Vermietung',
    rentalDesc: 'Unsere Produkte sind direkt zum Kauf oder zur Miete über unsere Partner verfügbar. Wir lagern auch alle Ersatzteile und Zubehörteile, die Sie benötigen könnten.',
    technicalKnowHow: 'Technisches Know-how',
    technicalDesc: 'Haben Sie technische Fragen? Benötigen Sie Hilfe bei der Optimierung von Schalung, Materialrotationen und Schalungslösungen oder bei der Erstellung technischer Zeichnungen oder BIM-Modelle?',
    repairMaintenance: 'Reparatur und Wartung',
    repairDesc: 'Wir kümmern uns um die Werterhaltung Ihrer Schalung. Unser Service umfasst Reinigung, Plattenaustausch und Reparaturen bis hin zur kompletten Regeneration.',
    onsiteAssistance: 'Vor-Ort-Unterstützung',
    onsiteDesc: 'Benötigen Sie Schulungen für die Installation oder Wartung von Schalungen? Haben Sie ein Projekt und benötigen Beratung? Unser Team ist hier, um Sie zu unterstützen.',
    
    // Products Section
    popularProducts: 'Beliebte Produkte',
    wallFormwork: 'Wandschalung',
    alphaNDesc: 'Alpha N ermöglicht eine homogene Materialisierung von Fugen und Plattenlöchern und erfüllt damit die ästhetischen Anforderungen von Sichtbeton.',
    aluBDesc: 'Das AluB-System ist eine tragbare Aluminium-Schalungslösung, die für die Herstellung von geraden Betonwänden in Standardhöhe entwickelt wurde. Es ist besonders geeignet für Baustellen ohne Kräne oder in schwer zugänglichen Bereichen.',
    starTecDesc: 'Die StarTec XT Schalung kombiniert drei Verankerungsmethoden dank der integrierten Combi-Stabführung.',
    
    // Projects Section
    ourProjects: 'Unsere Projekte',
    modernOffice: 'Modernes Bürogebäude',
    commercialConstruction: 'Gewerbebau',
    highRise: 'Hochhausentwicklung',
    residentialComplex: 'Wohnkomplex',
    contemporaryMuseum: 'Zeitgenössisches Museum',
    culturalArchitecture: 'Kulturarchitektur',
    
    // Contact Section
    contactTitle: 'Lassen Sie unser Team Ihnen helfen, das richtige Produkt und den richtigen Service zu wählen.',
    contactDesc: 'Sprechen Sie mit einem unserer AlphaTechSystems-Schalungsspezialisten; wir können Ihnen bei allen Ihren Schalungsbedürfnissen helfen. Lassen Sie uns Ihnen bei Ihrem nächsten Schalungsprojekt helfen.',
    salesDirector: 'Verkaufsleiter für die französischsprachige Schweiz',
    viewLinkedIn: 'LinkedIn-Profil anzeigen',
    sendEmail: 'Senden Sie mir eine E-Mail',
    
    // Contact Form
    firstName: 'Vor- und Nachname',
    emailAddress: 'E-Mail-Adresse',
    phoneNumber: 'Telefon',
    yourMessage: 'Ihre Nachricht',
    requiredFields: '* Diese Felder sind erforderlich',
    dataProtection: 'Datenschutz',
    privacyPolicy: 'Ich habe die Datenschutzrichtlinie gelesen und akzeptiere sie',
    newsletter: 'Ich möchte den Newsletter abonnieren.',
    sendMessage: 'Nachricht senden',
    
    // Footer translations
    companyDescription: 'Specialisten in der Herstellung und dem Verkauf von Schalungsausrüstung. AlphaTech ist ein Familienunternehmen mit internationaler Reichweite. Mit über 40 Jahren weltweit sind wir stolz auf das Vertrauen in mehr als 40 Ländern. Der Hauptsitz befindet sich in Haiterbach, Deutschland. Seien Sie die Ersten. Bauen Sie intelligent.',
    footerPopularProducts: 'Beliebte Produkte',
    alphaTechServices: 'AlphaTech Services',
    footerRental: 'Vermietung',
    engineering: 'Ingenieurwesen',
    onSiteGuidance: 'Vor-Ort-Betreuung',
    refurbishment: 'Aufarbeitung',
    preAssembly: 'Vormontage',
    academy: 'Akademie',
    tools: 'Werkzeuge',
    downloads: 'Downloads',
    bimTools: 'BIM-Tools',
    wallThicknessCalculator: 'Wanddicken-Druckrechner',
    columnFormsCalculator: 'Rechner für Stützenschalungen',
    footerContact: 'Kontakt',
    alphaTechFormworkSystems: 'AlphaTech Formwork Systems Ltd',
    alphaTechUK: 'AlphaTech UK',
    alphaTechSpain: 'AlphaTech Spain',
    international: 'International',
    allRightsReserved: 'Alle Rechte vorbehalten.',
    terms: 'Bedingungen',
    legalNotice: 'Impressum',
    privacyPolicyFooter: 'Datenschutzerklärung',
    visitSocialMedia: 'Besuchen Sie uns in den sozialen Medien:',
    
    // Products Page translations
    ourFormworkProducts: 'Unsere Schalungsprodukte',
    productsHeroDesc: 'Entdecken Sie unsere Premium-Schalungslösungen, die für Effizienz, Langlebigkeit und Vielseitigkeit in allen Bauprojekten entwickelt wurden.',
    allProducts: 'Alle Produkte',
    productsWallFormwork: 'Wandschalung',
    columnFormwork: 'Säulenschalung',
    showeringTower: 'Duschturm',
    accessPlatforms: 'Zugangs- und Sicherheitsplattformen',
    accessories: 'Zubehör',
    availableRental: 'Zur Miete verfügbar',
    craneIndependent: 'Kranunabhängig',
    heavyFormwork: 'Schwere Schalung',
    singleSidedFormwork: 'Einseitig verankerte Schalung',
    hydraulicClimber: 'Hydraulischer Kletterer',
    productsAlphaNDesc: 'Alpha N ermöglicht eine homogene Materialisierung von Fugen und Plattenlöchern und erfüllt damit die ästhetischen Anforderungen von Sichtbeton.',
    productsAluBDesc: 'AluB ist eine universelle, handliche Schalung aus Aluminium. Leicht und einfach zu handhaben, bietet sie Vielseitigkeit für eine breite Palette von Bauanwendungen.',
    starTecXTDesc: 'Die StarTec XT-Schalung kombiniert drei Verankerungsmethoden dank der integrierten Combi-Stabführung und bietet außergewöhnliche Vielseitigkeit und Effizienz.',
    aluminumConstruction: 'Aluminium-Konstruktion',
    universalApplication: 'Universelle Anwendung',
    tripleAnchoringSystem: 'Dreifach-Verankerungssystem',
    viewDetails: 'Details Anzeigen',
    compareProducts: 'Unsere Produkte Vergleichen',
    compareDesc: 'Finden Sie die perfekte Schalungslösung für Ihre spezifischen Baubedürfnisse.',
    features: 'Eigenschaften',
    material: 'Material',
    aluminum: 'Aluminium',
    aluminumSteel: 'Aluminium mit Stahlverstärkung',
    steel: 'Stahl',
    weight: 'Gewicht',
    lightweight: 'Leichtgewicht (20 kg/m²)',
    medium: 'Mittel (23 kg/m²)',
    heavyDuty: 'Schwerlast (45 kg/m²)',
    freshConcretePressure: 'Frischbetondruck',
    bestFor: 'Am Besten Für',
    smallMediumProjects: 'Kleine bis mittlere Projekte',
    mediumLargeProjects: 'Mittlere bis große Projekte',
    largeCommercial: 'Große Gewerbe- und Infrastruktur',
    specialFeature: 'Besondere Eigenschaft',
    optimizedHeights: 'Optimierte Höhen',
    enhancedDurability: 'Verbesserte Haltbarkeit',
    tripleAnchoring: 'Dreifach-Verankerungssystem',
    needHelpChoosing: 'Brauchen Sie Hilfe bei der Auswahl der richtigen Schalung?',
    expertConsultation: 'Unser Expertenteam kann Ihnen helfen, die beste Schalungslösung für Ihre spezifischen Baubedürfnisse zu bestimmen. Kontaktieren Sie uns noch heute für eine persönliche Beratung.',
    contactUs: 'Kontaktieren Sie Uns',
    
    // AlphaN Product Page translations
    alphaNHeroDesc: 'Leicht. Modular. Effizient. Die nächste Generation der tragbaren Schalung.',
    alphaNProductDesc: 'Jede Baustelle ist anders und hat ihre eigenen Anforderungen. Das Alpha N Schalungssystem wurde entwickelt, um diesen Anforderungen mit maximaler Flexibilität gerecht zu werden. Modular passt es sich an alle Konfigurationen an und stellt sicher, dass Sie immer die richtige Ausrüstung haben, unabhängig von der Komplexität der Struktur.',
    details: 'Details',
    qualityFacingConcrete: 'Qualität des Sichtbetons gewährleistet',
    qualityFacingDesc: 'Dank einer symmetrischen Anordnung der Stabdurchgänge und verschiedener Plattengrößen ermöglicht Alpha N eine homogene Materialisierung von Fugen und Plattenlöchern und erfüllt damit die ästhetischen Anforderungen von Sichtbeton.',
    assemblyAnchoringSystem: 'Montage- und Verankerungssystem',
    alphaTechLock: 'AlphaTECH-Verschluss:',
    alphaTechLockDesc: 'schnelle Befestigung von Platten mit einfachen Hammerschlägen',
    multiFunctionCrossbeam: 'Multifunktions-Querträger:',
    multiFunctionDesc: 'Angeschweißte DW-Muttern für schnelle Installation von Zubehör mit einem Stück – der Flanschschraube',
    anchoringSystem: 'Verankerungssystem:',
    anchoringSystemDesc: 'DW Ø 15 mm mit 80 kN Tragfähigkeit doppelseitig',
    easeOfUse: 'Benutzerfreundlichkeit',
    identicalFaces: 'Identische Flächen:',
    identicalFacesDesc: 'keine Fehler, schnellere Installation',
    layout: 'Layout:',
    layoutDesc: 'symmetrische horizontale und vertikale Installation',
    corners: 'Ecken:',
    cornersDesc: 'Ecklösungen, die für alle Wandstärken implementiert werden können, mit einem vollständigen Sortiment:',
    cornerTypes: 'Innen-, Außen-, Scharnier- und Schrägecken',
    outerCorners: 'Drei Außenecken (0,5 cm und 10 cm auf jeder Seite)',
    insideCorner: 'Innenecke (30 cm auf jeder Seite)',
    technicalSpecifications: 'Technische Spezifikationen',
    maximumAdaptability: 'Maximale Anpassungsfähigkeit',
    panelDimensions: 'Plattenabmessungen:',
    heights: 'Höhen:',
    heightsValues: '330 cm, 270 cm, 150 cm',
    widths: 'Breiten:',
    widthsValues: 'von 270 cm bis 30 cm (240 cm, 120 cm, 90 cm, 60 cm, 50 cm, 45 cm, 40 cm)',
    customSizes: 'Weitere maßgeschneiderte Größen verfügbar',
    adaptabilityDesc: 'Diese Abmessungen ermöglichen es, sich schnell an die Geometrie des Gebäudes anzupassen und alle üblichen Wandstärken ohne Ausgleichsteile zu erreichen.',
    technicalPerformance: 'Technische Leistung',
    permissiblePressure: 'Zulässiger Druck',
    pressureValue: '80 kN/m² für eine einfache Wand',
    materialSpec: 'hochdimensionaler, torsionsresistenter Stahl',
    coating: 'Beschichtung',
    coatingValue: '220 g/m² Phenolharz beidseitig',
    painting: 'Lackierung',
    paintingValue: 'elektromatisch',
    crane: 'Kran',
    craneValue: 'erfordert die Verwendung eines Krans',
    applicationExamples: 'Anwendungsbeispiele',
    residentialConstruction: 'Wohnungsbau',
    residentialDesc: 'Perfekt für Fundamentwände und Kellerbau in Wohnprojekten.',
    commercialBuildings: 'Gewerbebauten',
    commercialDesc: 'Ideal für kleine bis mittlere gewerbliche Bauprojekte.',
    infrastructureProjects: 'Infrastrukturprojekte',
    infrastructureDesc: 'Verwendet in kleineren Infrastrukturelementen wie Stützmauern und Fundamenten.',
    interestedInAlphaFix: 'Interessiert an AluFix für Ihr Projekt?',
    alphaFixContactDesc: 'Kontaktieren Sie unser Team für ein Angebot oder um mehr darüber zu erfahren, wie AluFix Ihrem Bauprojekt zugute kommen kann.',
    youMightAlsoLike: 'Das Könnte Ihnen Auch Gefallen',
    aluStarDesc: 'Robustes Aluminium-Schalungssystem für große Betonkonstruktionen.',
    plyformDesc: 'Vielseitiges Sperrholz-Schalungssystem für Wände, Säulen und Platten.',
    tableFormDesc: 'Fliegendes Formsystem für effizienten Plattenbau in Hochhäusern.',
    
    // AluB Product Page translations
    aluBHeroDesc: 'Universal. Langlebig. Vielseitig. Das Aluminium-Schalungssystem für alle Ihre Baubedarf.',
    aluBProductDesc: 'Das AluB-System ist eine manuportable Aluminium-Schalungslösung, die für die Herstellung gerader Betonwände in Standardhöhe entwickelt wurde. Es eignet sich besonders für Baustellen ohne Krane oder in schwer zugänglichen Bereichen.',
    keyBenefits: 'Hauptvorteile',
    manuportable: 'Manuportabel',
    manuportableDesc: 'Kein Kran erforderlich – einfache Handhabung durch eine Person.',
    lightweightEfficient: 'Leicht und effizient',
    lightweightEfficientDesc: 'Ca. 21,5 kg/m² für ein ausgezeichnetes Gewichts-/Festigkeitsverhältnis.',
    optimalModularity: 'Optimale Modularität',
    optimalModularityDesc: 'Große Auswahl an Standardplatten (270 x 90, 60, 50, 30 cm) + maßgeschneiderte Konstruktion.',
    qualityFinish: 'Qualitätsfinish',
    qualityFinishDesc: '15 mm Birken-Vollsperrholz, 220 g Film – 1,5 mm Kunststofffilm-Option verfügbar.',
    aluBAdaptability: 'Anpassungsfähigkeit',
    aluBAdaptabilityPoint1: 'Möglichkeit, eine Holzlattung (bis zu 10 cm) zwischen zwei Platten hinzuzufügen, um die Breite anzupassen.',
    aluBAdaptabilityPoint2: 'Eck- und Stabilisierungszubehör für alle Konfigurationen verfügbar.',
    enhancedSecurity: 'Erhöhte Sicherheit',
    enhancedSecurityPoint1: 'Service-Konsolen, Geländerpfosten, Druck-Zug-Stützen inklusive.',
    enhancedSecurityPoint2: 'Stabilitäts- und Zugangsaccessoires lackiert für bessere Sichtbarkeit.',
    technicalCharacteristics: 'Technische Eigenschaften',
    specification: 'Spezifikation',
    aluBDetailsHeader: 'Details',
    materialAluminum: 'Aluminium (größtenteils recycelt)',
    panelCovering: 'Plattenbeschichtung',
    panelCoveringValue: '15 mm Birkensperrholz, 220 g Film – optional 1,5 mm Kunststofffilm',
    edgeProfileThickness: 'Randprofildicke',
    edgeProfileValue: '100 mm',
    standardDimensionsHeight: 'Standardabmessungen - Höhe',
    standardHeightValue: '270 cm',
    standardDimensionsWidths: 'Standardabmessungen - Breiten',
    standardWidthsValue: '90, 60, 50, 30 cm + maßgeschneidert',
    aluBWeight: 'Gewicht',
    aluBWeightValue: '21,5 kg/m² | Platte 270 x 90 cm ≈ 65 kg',
    aluBAnchoring: 'Verankerung',
    anchoringValue: 'DW-System Ø15 mm, doppelseitige Klemmung',
    numberOfRods: 'Anzahl der Stangen',
    numberOfRodsValue: '3 vertikale Stangen für H 270 cm und 300 cm Platten',
    permissibleConcretePressure: 'Zulässiger Betondruck',
    concretePressureValue: '30 Tonnen/m²',
    aluBCommercialConstruction: 'Gewerbebau',
    aluBCommercialConstructionDesc: 'Ideal für mittlere bis große Gewerbebauten mit komplexen Betonanforderungen.',
    multiStoryBuildings: 'Mehrstockige Gebäude',
    multiStoryBuildingsDesc: 'Perfekt für den Bau von Wänden in mehrstockigen Wohn- und Bürogebäuden.',
    infrastructureBridges: 'Infrastrukturprojekte',
    infrastructureBridgesDesc: 'Verwendet in Brücken, Tunneln und anderen mittelgroßen Infrastrukturelementen.',
    interestedInAluStar: 'Interessiert an AluStar für Ihr Projekt?',
    aluStarContactDesc: 'Kontaktieren Sie unser Team für ein Angebot oder um mehr darüber zu erfahren, wie AluStar Ihrem Bauprojekt zugute kommen kann.',
    aluFixDesc: 'Leichtes, tragbares Schalungssystem für effizienten Bau.',
    
    // Countries
    swiss: 'Schweiz',
    france: 'Frankreich',
    germany: 'Deutschland',
    other: 'Andere',
    
    // Services Page
    whatWeOffer: 'Was wir anbieten',
    servicesDescription: 'Wir bieten umfassende Baulösungen, die auf Ihre spezifischen Bedürfnisse zugeschnitten sind, von der Planung bis zur Ausführung.',
    constructionPlanning: 'Bauplanung',
    constructionPlanningDesc: 'Umfassende Planungsdienstleistungen, die sicherstellen, dass Ihr Projekt mit einem soliden Fundament beginnt. Unsere Experten analysieren Anforderungen, entwickeln Zeitpläne und erstellen detaillierte Ausführungspläne.',
    projectManagement: 'Projektmanagement',
    projectManagementDesc: 'End-to-End-Projektmanagement-Services, die sicherstellen, dass Ihr Bauprojekt pünktlich, im Budget und nach höchsten Qualitätsstandards abgeschlossen wird.',
    formworkSolutions: 'Schalungslösungen',
    formworkSolutionsDesc: 'Spezialisierte Schalungslösungen für Betonkonstruktionen aller Art. Wir bieten fortschrittliche Systeme, die Präzision, Effizienz und Sicherheit gewährleisten.',
    concreteWorks: 'Betonarbeiten',
    concreteWorksDesc: 'Fachkundige Betondienstleistungen einschließlich Gießen, Finishing und spezialisierte Behandlungen. Wir gewährleisten Haltbarkeit, ästhetische Anziehungskraft und strukturelle Integrität.',
    consultingServices: 'Beratungsdienstleistungen',
    consultingServicesDesc: 'Professionelle Beratung zu Baumethoden, Materialauswahl und technischen Lösungen zur Optimierung der Effizienz und Kosteneffektivität Ihres Projekts.',
    equipmentRental: 'Geräteverleih',
    equipmentRentalDesc: 'Umfassende Geräteverleih-Services einschließlich Schalungssysteme, Gerüste und spezialisierte Bauwerkzeuge zur Unterstützung Ihrer Projektanforderungen.',
    learnMore: 'Mehr erfahren',
    whyChooseOurServices: 'Warum unsere Services wählen',
    qualityAssurance: 'Qualitätssicherung',
    qualityAssuranceDesc: 'Wir halten die höchsten Qualitätsstandards in allen unseren Services ein und gewährleisten dauerhafte und zuverlässige Ergebnisse.',
    timelyDelivery: 'Pünktliche Lieferung',
    timelyDeliveryDesc: 'Wir verstehen die Wichtigkeit von Terminen und stellen sicher, dass alle Projekte termingerecht abgeschlossen werden.',
    expertTeam: 'Expertenteam',
    expertTeamDesc: 'Unser Team besteht aus erfahrenen Fachleuten mit tiefgreifendem Wissen in verschiedenen Bauspezialitäten.',
    readyToStartProject: 'Bereit, Ihr Projekt zu starten?',
    servicesCtaDesc: 'Kontaktieren Sie uns heute, um zu besprechen, wie unsere Services dabei helfen können, Ihr Bauprojekt zum Leben zu erwecken.',
    getInTouch: 'Kontakt aufnehmen',
    
    // Contact Page
    contactUsTitle: 'Kontakt',
    contactFormName: 'Name',
    contactFormEmail: 'E-Mail',
    contactFormMessage: 'Nachricht',
    contactFormSend: 'Nachricht senden',
    contactInformation: 'Kontaktinformationen',
    contactAddress: 'Adresse',
    contactAddressValue: '123 Baustraße, Baustadt, 10001',
    contactPhone: 'Telefon',
    contactPhoneValue: '+41 79 775 77 81 | +41 21 991 33 33',
    contactEmailLabel: 'E-Mail',
    contactEmailValue: 'info@alphatechsystemes.com',
    workingHours: 'Öffnungszeiten',
    workingHoursWeekdays: 'Montag - Freitag: 8:00 - 18:00',
    workingHoursWeekends: 'Samstag - Sonntag: Geschlossen'
  }
};
END removed legacy translations */

// Merge modular translations only (legacy removed).
const translations = {
  en: {
    ...nav.en,
    ...hero.en,
    ...stats.en,
    ...leadership.en,
    ...services.en,
    ...productsHome.en,
    ...projects.en,
    ...contactSection.en,
    ...footer.en,
    ...contactForm.en,
    ...contactPage.en,
    ...productsPage.en,
    ...alphaNProductPage.en,
    ...aluBProductPage.en,
    ...aluBMaxProductPage.en,
    ...accessories.en,
  },
  fr: {
    ...nav.fr,
    ...hero.fr,
    ...stats.fr,
    ...leadership.fr,
    ...services.fr,
    ...productsHome.fr,
    ...projects.fr,
    ...contactSection.fr,
    ...footer.fr,
    ...contactForm.fr,
    ...contactPage.fr,
    ...productsPage.fr,
    ...alphaNProductPage.fr,
    ...aluBProductPage.fr,
    ...aluBMaxProductPage.fr,
    ...accessories.fr,
  },
  de: {
    ...nav.de,
    ...hero.de,
    ...stats.de,
    ...leadership.de,
    ...services.de,
    ...productsHome.de,
    ...projects.de,
    ...contactSection.de,
    ...footer.de,
    ...contactForm.de,
    ...contactPage.de,
    ...productsPage.de,
    ...alphaNProductPage.de,
    ...aluBProductPage.de,
    ...aluBMaxProductPage.de,
    ...accessories.de,
  },
} as const;

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load saved language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'fr', 'de'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    // Update document language attribute
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
